name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- this fixes the 403 error
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: rnzrysrio
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate contribution snake"
          add: "dist/github-contribution-grid-snake.svg"
          default_author: github_actions
